### ISSUE TITLE
Tighten Default RBAC Rules

### ISSUE THREAD

**Issue by christopherhein** [aws/aws-node-termination-handler#10]
First, great work on this! It seems like the RBAC could be paired down to a much tighter set of controls.

It looks like these have some overlapping rules, namely having `apiGroups: "", resources: "*"verbs: "*"` as well as all the rest of the declarations. I also wouldn't have `apiGroups: rbac.authorization.k8s.io, resources: "*", verbs: "*"`

```yaml
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-termination-handler
  namespace: default
rules:
- apiGroups:
  - "apps"
  resources:
  - "daemonsets"
  verbs:
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
```

**Comment by jillmon** [comment]
I've looked into this and run some tests removing the following duplicate rule:
```yaml
- apiGroups:
  - "apps"
  resources:
  - "daemonsets"
  verbs:
  - get
  - delete
```
Removing this rule results in a bunch of errors. 

`
[cannot delete daemonsets.apps "node-termination-handler" is forbidden: User "system:serviceaccount:default:node-termination-handler" cannot get resource "daemonsets" in API group "apps" in the namespace "default": default/node-termination-handler-j4mjp, cannot delete daemonsets.apps "aws-node" is forbidden: User "system:serviceaccount:default:node-termination-handler" cannot get resource "daemonsets" in API group "apps" in the namespace "kube-system": kube-system/aws-node-9f2l6, cannot delete daemonsets.apps "kube-proxy" is forbidden: User "system:serviceaccount:default:node-termination-handler" cannot get resource "daemonsets" in API group "apps" in the namespace "kube-system": kube-system/kube-proxy-f7lkk]
`


At this time I can't get the termination handler to work with any more restrictive RBAC rules.  If you have any testing that shows otherwise please let me know.

**Comment by christopherhein** [comment]
More important than the `daemonsets` would be `create` on `crds`, and doesn't:

```
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
```

And

```- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - "*"
  verbs:
  - "*"```

Which IIRC means if this container was compromised it could CRUD, `secrets`, `serviceaccounts` `roles`, `rolebindings`, `clusterroles` `clusterrolebindings` etc. 

/cc @mhausenblas @jicowan
