### ISSUE TITLE
Non-Helm install files still include helm annotations

### ISSUE THREAD

**Issue by mattrandallbecker** [aws/aws-node-termination-handler#100]
When "helm template" is used to generate the plain yaml files the helm specific labels are left on the resources.  The build step should remove lines like the bolded below after generation.

Example annotation labels
**helm.sh/chart: aws-node-termination-handler-0.5.0**
**app.kubernetes.io/managed-by: Helm**

Example yaml from 1.2.0 release
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-node-termination-handler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-node-termination-handler
    helm.sh/chart: aws-node-termination-handler-0.5.0
    app.kubernetes.io/instance: aws-node-termination-handler
    k8s-app: aws-node-termination-handler
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
```
