### ISSUE TITLE
Missing default values for heartbeat in Helm chart

### ISSUE THREAD

**Issue by koki-sato** [aws/aws-node-termination-handler#1135]
**Describe the bug**

Helm chart v0.26.0 does not have default values for heartbeat (added in https://github.com/aws/aws-node-termination-handler/pull/1116), so it is possible to generate a manifest that contains env with empty values.

**Steps to reproduce**

```yaml
$ helm upgrade --dry-run --install aws-node-termination-handler \
  --namespace kube-system \
  --set enableSqsTerminationDraining=true \
  oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler --version 0.26.0
...
---
# Source: aws-node-termination-handler/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: aws-node-termination-handler
          env:
            - name: HEARTBEAT_INTERVAL
              value:
            - name: HEARTBEAT_UNTIL
              value:
```

**Expected outcome**

I think it's a good idea to set `-1` as the default values for the helm chart according to the following:

https://github.com/aws/aws-node-termination-handler/blob/e07cd858724c1d686ac42d86cb1e3adeba355976/pkg/config/config.go#L238-L239

**Application Logs**

N/A

**Environment**

* NTH App Version: 1.24.0
* NTH Mode (IMDS/Queue processor): Queue processor
* OS/Arch:
* Kubernetes version: 
* Installation method: Helm
