### ISSUE TITLE
SQS tracker - slack notification

### ISSUE THREAD

**Issue by saar-win** [aws/aws-node-termination-handler#1141]
Hey, I've installed karpenter and want to get a notification from the SQS when a spot is terminating or changes.
Without ASG, etc, just the sqs.
When I use the nth (no imds mode), I get notifications for all my SQS env (dev/stag/prod)
Which type of NTH do I need to use? 
Which values?
I want to get a specific notification without trash.
Thanks!
```
queueURL: "https://sqs.xxxxx.amazonaws.com/xxxx/xxxx"

serviceAccount:
  name: nth-sa
  annotations:
    eks.amazonaws.com/role-arn: "xxx"

enableSqsTerminationDraining: true
checkTagBeforeDraining: true
checkASGTagBeforeDraining: true
enableSpotInterruptionDraining: true
enableRebalanceMonitoring: true
enableRebalanceDraining: true
managedAsgTag: ""
awsRegion: XXXX

webhookURL: https://hooks.slack.com/services/XX/XX/XXX

```
