### ISSUE TITLE
Make helm podAnnotations granular by daemonset / deployment

### ISSUE THREAD

**Issue by gillg** [aws/aws-node-termination-handler#304]
Annonation could be used for multiple things, but for example, with Kiam, you manage IAM roles virtualy attached to pods via these annotations.

NTH deployment, needs a specific role, but daemonset not needs it.
For now... I made a dirty trick to handle that.

```yaml
podAnnotations:
  iam.amazonaws.com/role: arn:aws:iam::xxxxxxxxxxx:role/xxxxxxxx-termination-handler
# Trick to not give permissions on deamonsets
linuxPodAnnotations:
  iam.amazonaws.com/role: ''
windowsPodAnnotations:
  iam.amazonaws.com/role: ''
```
