### ISSUE TITLE
component=warmer canonical_name=public.ecr.aws/aws-ec2/aws-node-termination-handler

### ISSUE THREAD

**Issue by mrad-bilel** [aws/aws-node-termination-handler#438]
Hey,

I've installed aws-node-termination-handler with helm chart , the deployment was Ok and DaemonSet pods have been deployed . 

I see this error in the logs any idea please how to fix this 

```
caller=warming.go:180 component=warmer canonical_name=public.ecr.aws/aws-ec2/aws-node-termination-handler auth={map[]} err="requesting tags: error parsing HTTP 404 response body: invalid character 'p' after top-level value: \"404 page not found\\n\""

```

```
helm ls
NAME                                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
aws-node-termination-handler            kube-system     1               2021-04-14 10:09:34.966599019 +0000 UTC deployed        aws-node-termination-handler-0.15.0     1.13.0  
````

Thanks in advance .

**Comment by bwagner5** [comment]
Which logs do you see the 404 in? The kubelet or the NTH logs?

**Comment by arthuralmeida93** [comment]
Having the same issue here. 

```
ts=2021-09-13T20:18:02.480587351Z caller=warming.go:180 component=warmer canonical_name=public.ecr.aws/aws-ec2/aws-node-termination-handler auth={map[]} err="requesting tags: error parsing HTTP 404 response body: invalid character 'p' after top-level value: \"404 page not found\\n\""

```

These logs are from my Flux CD instance which automates deployments in my K8s cluster. 

This is the helm-release.yaml I used to install the AWS Node Termination Handler in my cluster:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aws-node-termination-handler
  namespace: kube-system
spec:
  chart:
    repository: https://aws.github.io/eks-charts/
    name: aws-node-termination-handler
    version: 0.15.3
  values:
    nodeSelector:
      nodeGroup: spot
    enableSpotInterruptionDraining: "true"
    enableRebalanceMonitoring:  "true"
```
Versions:

- Kubernetes v1.18.20
- Flux v1.19.0

-----

What I've found about this error is that it may be related with the AWS ECR image incorrect naming, probably it contains an illegal character or illegal name.

https://stackoverflow.com/questions/59975147/docker-aws-ecr-error-parsing-http-404-response-body-invalid-character-p-after
